# Generated by Django 2.1.7 on 2019-04-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snypet',
            new_name='Snippet',
        ),
    ]
